local helpers = require("tests.helpers")

describe("neonpm.manager.detect", function()
  local manager, config, project

  before_each(function()
    helpers.reload()
    manager = require("neonpm.manager")
    config = require("neonpm.config")
    project = require("neonpm.project")
    config.reset()
    project.clear_cache()
    manager.clear_cache()
  end)

  it("honours the hard override from configuration", function()
    config.setup({ manager = "bun" })
    local found = manager.detect(helpers.fixture("npm-project"))
    assert.equals("bun", found.name)
    assert.equals("config", found.source)
  end)

  it("reads the packageManager field from package.json", function()
    local found = manager.detect(helpers.fixture("monorepo"))
    assert.equals("pnpm", found.name)
    assert.equals("packageManager", found.source)
  end)

  it("detects the manager from the lockfile", function()
    local found = manager.detect(helpers.fixture("npm-project"))
    assert.equals("npm", found.name)
    assert.equals("lockfile", found.source)
  end)

  it("finds a lockfile above the package root (monorepo)", function()
    local app = vim.fs.joinpath(helpers.fixture("monorepo"), "packages", "app")
    config.setup({})
    local found = manager.detect(app)
    assert.equals("pnpm", found.name)
    assert.equals("lockfile", found.source)
  end)

  it("bun is detected from bun.lock", function()
    local found = manager.detect(helpers.fixture("bun-project"))
    assert.equals("bun", found.name)
  end)

  it("berry is detected from .yarnrc.yml", function()
    local found = manager.detect(helpers.fixture("yarn-berry"))
    assert.equals("yarn", found.name)
    assert.is_true(found.opts.berry)
    assert.same({ "yarn", "up" }, found.build({ op = "update" }))
  end)

  it("falls back to npm without a lockfile", function()
    local found = manager.detect(helpers.fixture("no-lock"))
    assert.equals("npm", found.name)
    assert.equals("fallback", found.source)
  end)

  it("the bound manager builds argv without passing opts", function()
    local found = manager.detect(helpers.fixture("npm-project"))
    assert.same(
      { "npm", "install", "--save-dev", "vitest" },
      found.build({ op = "add", pkgs = { "vitest" }, dev = true })
    )
  end)

  it("does not serve a stale cache entry after the configuration changes", function()
    local root = helpers.fixture("npm-project")
    local first = manager.detect(root)
    assert.equals("npm", first.name)
    assert.equals("lockfile", first.source)

    config.setup({ manager = "bun" })
    local second = manager.detect(root)
    assert.equals("bun", second.name)
    assert.equals("config", second.source)
  end)

  it("berry override walks upward for .yarnrc.yml, not just the root itself", function()
    config.setup({ manager = "yarn" })
    local app = vim.fs.joinpath(helpers.fixture("yarn-berry"), "packages", "app")
    local found = manager.detect(app)
    assert.equals("yarn", found.name)
    assert.equals("config", found.source)
    assert.is_true(found.opts.berry)
    assert.same({ "yarn", "up" }, found.build({ op = "update" }))
  end)
end)
